import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { MemoryManager } from '../memory/MemoryManager';
import { HandoffPromptBuilder } from './HandoffPromptBuilder';

const BEGIN = '<!-- AICB:BEGIN — auto-generated by AI Context Bridge. Do not edit between markers. -->';
const END = '<!-- AICB:END -->';

const DEFAULT_AGENT_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'AGENT.md',
  'GEMINI.md',
  '.cursorrules',
  '.windsurfrules',
  '.github/copilot-instructions.md',
];

export class AgentBridgeWriter implements vscode.Disposable {
  private readonly disposables: vscode.Disposable[] = [];
  private flushHandle: NodeJS.Timeout | undefined;

  constructor(
    private readonly memory: MemoryManager,
    private readonly builder: HandoffPromptBuilder,
  ) {}

  start(): void {
    this.disposables.push(memory_listen(this.memory, () => this.scheduleFlush()));
    this.disposables.push(
      vscode.workspace.onDidChangeConfiguration((e) => {
        if (
          e.affectsConfiguration('aiContextBridge.exportToAgentFiles') ||
          e.affectsConfiguration('aiContextBridge.agentFiles')
        ) {
          this.scheduleFlush();
        }
      }),
    );
  }

  private cfg() {
    const c = vscode.workspace.getConfiguration('aiContextBridge');
    return {
      enabled: c.get<boolean>('exportToAgentFiles', false),
      files: c.get<string[]>('agentFiles') ?? DEFAULT_AGENT_FILES,
      onlyExisting: c.get<boolean>('agentFilesOnlyExisting', true),
    };
  }

  private scheduleFlush(): void {
    if (this.flushHandle) {
      clearTimeout(this.flushHandle);
    }
    this.flushHandle = setTimeout(() => {
      void this.flushNow();
    }, 1500);
  }

  async flushNow(opts?: { force?: boolean }): Promise<{ written: string[]; skipped: string[] }> {
    const cfg = this.cfg();
    const written: string[] = [];
    const skipped: string[] = [];
    if (!cfg.enabled && !opts?.force) {
      return { written, skipped };
    }
    const folder = vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
    if (!folder) {
      return { written, skipped };
    }
    const block = wrap(this.builder.build());
    for (const rel of cfg.files) {
      const target = path.join(folder, rel);
      try {
        const exists = await pathExists(target);
        if (!exists && cfg.onlyExisting) {
          skipped.push(rel);
          continue;
        }
        await fs.promises.mkdir(path.dirname(target), { recursive: true });
        const original = exists ? await fs.promises.readFile(target, 'utf8') : '';
        const merged = mergeBlock(original, block);
        if (merged === original) {
          continue;
        }
        await atomicWrite(target, merged);
        written.push(rel);
      } catch {
        skipped.push(rel);
      }
    }
    return { written, skipped };
  }

  dispose(): void {
    if (this.flushHandle) {
      clearTimeout(this.flushHandle);
    }
    this.disposables.forEach((d) => d.dispose());
  }
}

function wrap(content: string): string {
  return `${BEGIN}\n${content}\n${END}`;
}

function mergeBlock(original: string, block: string): string {
  const beginIdx = original.indexOf(BEGIN);
  const endIdx = original.indexOf(END);
  if (beginIdx >= 0 && endIdx > beginIdx) {
    return original.slice(0, beginIdx) + block + original.slice(endIdx + END.length);
  }
  if (original.length === 0) {
    return block + '\n';
  }
  return original.replace(/\s*$/, '') + '\n\n' + block + '\n';
}

async function pathExists(p: string): Promise<boolean> {
  try {
    await fs.promises.access(p);
    return true;
  } catch {
    return false;
  }
}

async function atomicWrite(target: string, content: string): Promise<void> {
  const tmp = `${target}.aicb.tmp`;
  await fs.promises.writeFile(tmp, content, 'utf8');
  await fs.promises.rename(tmp, target);
}

function memory_listen(memory: MemoryManager, fn: () => void): vscode.Disposable {
  return memory.onDidChange((c) => {
    if (c.kind === 'thought' || c.kind === 'pinned' || c.kind === 'skill' || c.kind === 'killSwitch' || c.kind === 'bulk') {
      fn();
    }
  });
}
